services:
  worker1:
    build: ./worker1
    container_name: worker1_container
    volumes:
      - ./data:/var/data
      - ./result-1:/var/result

  worker2:
    build: ./worker2
    container_name: worker2_container
    volumes:
      - ./result-1:/var/data
      - ./result:/var/result
    depends_on:
      worker1:
        condition: service_completed_successfully
